version: "3.9"

volumes:
  letsencrypt:
  registry:

services:

  traefik:
    image: "traefik:v2.9.5"
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
     # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL?Variable not set}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  registry:
    image: registry:2
    volumes:
      - registry:/var/lib/registry
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.routers.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.rule=Host(`${DOMAIN?Variable not set}`)"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls.certresolver=letsencrypt"
        - "traefik.http.routers.registry.middlewares=auth-registry"
        - "traefik.http.middlewares.auth-registry.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}"
